language: java
jdk: oraclejdk8
sudo: required

stages:
- name: build
- name: tag
  if: tag = true

jobs:
  include:
  - stage: build
    script: echo "---BUILD---"
  - stage: tag
    script: echo "---TAG---"