language: java
jdk: oraclejdk8
sudo: required

stages:
- name: build
- name: tag
  if: branch =~ ^v[0-9]

jobs:
  include:
  - stage: build
    script: echo "---BUILD---"
  - stage: tag
    script: echo "---TAG---"